#!/usr/bin/env perl
use strict; use warnings; use v5.34;
#** @file
# @class DeconLogGLT
# @brief Stats from 3dDeconvolve log
#
# 20220728WF - init
# 20250731WF - docs
#*

package DeconLogGLT;
sub DeconLogGLT(){
  #** @fn public DeconLogGLT
  # @brief read a 3dDeconvolve log file to extract LC and h stats
  # @param name prefix column to add for all matches from stdin. Likely seed or permutation type
  # @verbatim
  #  useful for extracting many runs of '3dDeconvolve -nodata' during event timing optimization
  # @endverbatim
  #*
  my $name=$ARGV[0];
  my %h;
  my %_h;
  my $key;
  while($_=<STDIN>){
     $key=$2 if /(Gen|Stim).*: ([^ ]*)/;
     $h{$name}{"${key}_$1"}=$2 if /^\W+(LC|h).*=.*?([0-9.]+)/;
  }
  
  my @vals=sort (keys %{$h{(keys %h)[0]}});
  say join("\t","name",@vals);
  for my $f (keys %h){
    %_h = %{$h{$f}};
    say join("\t",$f, @_h{@vals} );
  }
}
DeconLogGLT unless(caller);
1;
