#!/usr/bin/env perl
use PDL;
use PDL::IO::Nifti;
# one voxel shift
# 84      100     84      1       old 2.3.nii
# 83      99      83      1        2.3.nii
#
# 96      114     96      1       old 2.nii
# 97      115     97      1        2.nii
#
# 64      76      64      1       old 3.nii
# 65      77      65      1        3.nii
my $badfile = "/Volumes/Zeus/preproc/petrest_rac1/MHRest_FM_ica/11403_20151106/wdktm_func.nii.gz";
open my $niifh, $badfile or die "cannot open $badfile";
my $nii=PDL::IO::Nifti->new(); 
$nii->read_nii($niifh);

