#!/usr/bin/env bash
set -euo pipefail
env | grep ^DRYRUN= && DRYRUN=echo || DRYRUN=""
[ -v NOECHOCHECK ] && NOECHOCHECK="check" || NOECHOCHECK=""

#
#run dcm2niix with 3dNotes wrapper. check for existing file
#
#  20201016WF  init
#  20210113WF  use rename-recent. nest into "main" (source for testing)
usage() {
cat <<HEREDOC
USAGE:
   $(basename "$0") output.nii.gz path/to/dcm/

   output.nii.gz - 1st argument is the output nifti. must end in .nii.gz
   path/to/dcm   - 2nd arg must be a folder or single dicom
                   escape spaces in input


   will
     * recursively make directories. be careful.
     * skip if already exists
     * add annotation with source directory to nifti. careful not to spill participant information
     * try to deal with gre fieldmap naming weirdness (if output matches magnitude[12] or phase)
   use DRYRUN=1 $(basename $0) ...  to test
HEREDOC
   exit 1
}

# rename mag and phase
# dcm2niix adds e.g. _e2 or _ph
# extracted here for testing (t/mknii.bats)
# also need to check we have a working 'rename' command
# only needed for mag and phase. so only check when we need one of those
_rename-recent(){
  rename-recent have? >/dev/null || exit 1 # dont convert if we have the wrong rename
  rename-recent "$@"
}
rename-mag(){
  local pattern='s/[12]?_e(\d.(nii.gz|json))$/$1/'
  local outdir="$1";shift
  # if input is magnitude.nii.gz and maginguted_e2.nii.gz
  # make first look like magnitude_e1 for later rename
  find $outdir -maxdepth 1 -mtime -1 -name '*magnitude*e2*.nii.gz' |grep -q magnitude &&
     _rename-recent 's/magnitude(.nii.gz|.json)$/magnitude_e1$1/' $outdir "*magnitude.*"

  _rename-recent "$pattern" "$outdir" "$@"
}
rename-phase(){
  local pattern='s/_e\d+(_ph)?(.nii.gz|.json)$/$2/'
  _rename-recent "$pattern" "$@"
}

main(){
  [ $# -ne 2 ] && usage
  nii_out="$1"; shift
  dcm_folder="$@"; shift
  [ -r "$nii_out" ] && echo "# have '$nii_out'" && exit 0
  test -r "${nii_out/magnitude.nii.gz/magnitude1.nii.gz}" && echo "# have '$_', considering that the same as '$nii_out'" && exit 0
  test -z "$NOECHOCHECK" -a -r "${nii_out/.nii.gz/_e1.nii.gz}" &&
     echo "# have '$_', considering that the same as '$nii_out' (set export NOECHOCHECK=check)" && exit 0
  [ ${nii_out:(-7)} != ".nii.gz" ] && echo "output must have .nii.gz extention!" && exit 1
  
  # should let dcm2niix just fail instead of doing the work here?
  # [ $(find -L "$dcm_folder" \( -type f -or -type l \) -print -quit|wc -l) -le 0  ] && echo "# '$dcm_folder' DNE or is empty?" && exit 1
  
  outname="$(basename "$nii_out" .nii.gz)"
  outdir="$(dirname "$nii_out")"
  [ ! -d "$outdir" ] && $DRYRUN mkdir -p "$outdir"
  
  #pretimestamp=$(mktemp /tmp/dcmnii_XXXXXX) # -newercm $pretimestamp 
  # TODO: add trap to cleanup file?
  $DRYRUN dcm2niix -z y -b y -f "$outname" -o "$outdir" "$dcm_folder" 
  [ -n "$DRYRUN" ] && exit 0
  # if above failed, script would bail (set -e)
  # so if we don't have the file it's probably has multiple echos
  case  $outname in 
     *magnitude|*magnitude[12]) 

       rename-recent have? || exit 1 # dont convert if we have the wrong rename
       # 20210113
       # dcm2nii  v1.0.2018 (ginger) only puts _e2 on the second echo
       # if we have _e2 and no _e1, the no _e* version is magnitude1
       [ -r $outdir/*magnitude.nii.gz -a -r $outdir/*magnitude_e2.nii.gz ] && 
	 rename-recent 's/magnitude\.(nii.gz|json)$/_e1.$1/' $outdir "*magnitude\.*" -v
       rename-recent 's/[12]?_e(\d.(nii.gz|json))$/$1/' $outdir "$outname*" -v

       # update output for 3dNotes and final check
       [[ $outname =~ magnitude$ ]] && nii_out="$outdir/${outname}1.nii.gz"
     ;;
     *phase|*phasediff)
       rename-recent have? || exit 1 # dont convert if we have the wrong rename
       rename-recent 's/_e\d+(_ph)?(.nii.gz|.json)$/$2/' $outdir "$outname*"
     ;;
      *task-*_bold)
         # add rest taskname to json sidecar
         local task
         [[ $outname =~ task-([^-_.]*) ]] && task=${BASH_REMATCH[1]}
         if [ -z "$task" ]; then echo "WARNING: unknown taskname for $outdir/$outname!"; else 
            grep -L TaskName "$outdir/$outname.json" |xargs -r sed -i "s/^{/{\\n  \"TaskName\": \"$task\",/"
         fi
     ;;
  esac
  
  if [ ! -r "$nii_out" ]; then
     echo -e "ERROR: did not create '$nii_out'.\n\t'$dcm_folder' has a multi echo sequence??!"
     echo "NOTE: $0 can deal with this if the output name ends with 'magnitude1.nii.gz' or 'phase.nii.gz'"
     exit 1
  fi
  
  # 3dNotes likes to complain. silence it
  export AFNI_NIFTI_TYPE_WARN=NO
  export AFNI_NO_OBLIQUE_WARNING="YES"
  $DRYRUN 3dNotes -h "$0 $dcm_folder $nii_out" "$nii_out" 
}
[[ "$(caller)" != "0 "* ]] && set +u || main "$@"
