#!/usr/bin/env bash

[ -z "${DRYRUN:-}" ] && DRYRUN= || DRYRUN="echo"

# 20210317WF - add user
#
# setup default groups and put ni config in .bashrc
#

# important groups on server
_USER_GROUPS=lncd,luna_wallace,kvm,docker,users

mkpass(){
   # concat nwords
   local n_words=3
   local min_word_len=5
   LC_ALL=C grep -P "[a-z]{$min_word_len}" /usr/share/dict/words |
      shuf -n $n_words|
      sed 's/.*/\u&/'|
      tr -dC '[A-Za-z]'
}
user_dne(){
  local user="$1"
  grep -q "$user" /etc/passwd && echo "have $user in $_" && return 1
  return 0
}
add_rhea_user(){
   local user="$1"; shift
   local fullname="$*"
   $DRYRUN useradd -g lncd -m -G "$_USER_GROUPS" -s "$(which bash)" -c "$fullname" $user
}
set_passwd(){
   local user="$1"; shift
   local pass="${1:-}"
   [ -z "$pass" ] && pass=$(mkpass)
   echo -e "$pass\n$pass" | $DRYRUN passwd "$user"
   echo "# using '$pass'"
}
add_rc(){
   # add default ni settings: env (path, python, fsl, afni, ...) and bash prompt, aliases, etc
   local user="$1"
   echo "source /opt/ni_tools/dotfiles/bash/.bashrc" |
      sudo -u "$user" $DRYRUN tee -a "/home/$user/.bashrc" >/dev/null

   # R config file: make sure we look to ni_tools for packages
   $DRYRUN sudo -u "$user" ln -s /opt/ni_tools/dotfiles/Rprofile/.Rprofile "/home/$user/"
}

# if running (not sourcing)
if [[ "$(caller)" == "0 "* ]]; then
   # run as root
   if [ "$(id -u)" -ne 0 ]; then
     sudo --preserve-env=DRYRUN,USERPASS "$0" "$@"
     exit $?
   fi

   # parse args
   [ $# -lt 2 ] && echo "USAGE: USERPASS=xxx $0 user full name # if no userpass, makes one up" && exit 1
   user="${1//@*/}"; shift
   fullname="$*";

   # already have user
   user_dne "$user" || exit

   add_rhea_user "$user" "$fullname"
   set_passwd "$user" "${USERPASS:-}"
   add_rc "$user"
fi
