#!/usr/bin/env bash
set -euo pipefail
#
# 20260226WF - init
# 20260405WF - noquiet checking SKIP_QUIET
#

REDO=${REDO:-0} # default: skip if exists. REDO !=0 means overwrite

noquiet() { [ -n "${SKIP_QUIET:-}" ] && return 0; echo "$*" >&2; }
usage(){
   [ $# -gt 0 ] && echo "$*"
   local c=$(basename $0)
  cat <<HERE
USAGE:
  $c  [-o] 'path/ouput/file/to/check' cmd-to-run

EXAMPLES:
  $c -o /tmp/date.txt date

  $c sub-1/mri/aseg.nii.gz recon-all -s sub-1
  DRYRUN=1 $c sub-1/mri/aseg.nii.gz recon-all -s sub-1
  REDO=1   $c sub-1/mri/aseg.nii.gz recon-all -s sub-1

  $c /tmp/date.txt sh -c "date > __SKIPFILE"

SYNOPSIS:
  'test -s' wrapper with REDO and verbose messaging support

   __SKIPFILE in cmd will be replaced by first argument

ENVIRONMENT:
   REDO=1  - overwrite (redo) even if output file exists
   DRYRUN=1   - only show what would be run
   SKIP_QUIET - dont report when skipping

NOTES:
  Watch out for redirection. DONT DO THIS
     $c /tmp/date.txt date > /tmp/date.txt # BAD BAD BAD

  Instead, use the -o or --output, like
     $c -o /tmp/date.txt date


  Alternatively, use an exported function

     writedate() { date > \$1; }; export -f writedate
     $c /tmp/date.txt writedate /tmp/date.txt

  or a dedicated shell

     $c /tmp/date.txt sh -c 'date > /tmp/date.txt'

  But maybe '$c' is overkill for your usage. Consider:

     test -s /tmp/date.txt || date > \$_


ALSO SEE:
  dryrun drytee
HERE
}

[[ $# -eq 0 || "${1:-}" =~ ^-+h(help)?$ ]] && usage && exit 0

# check for argumetns
write_stdout=0
while [ $# -gt 0 ]; do
    case $1 in
        -o|--output) write_stdout=1; shift;;
        -*) echo "ERROR: unknown option $1. if '$1' is a file, use './$1''"; exit 1;;
        *) break;; # not an input argument to parse. skip to next
    esac
done


outfile="${1:?need two args. first is outfile}"; shift

[ $# -eq 0 ] &&
   usage "ERROR: not given a command to run if '$outfile' doesn't exist" >&2 &&
   exit 1

cmd=("${@//__SKIPFILE/"$outfile"}")
if [ -s "$outfile" ]; then
   [ "$REDO" == 0 ] &&
      noquiet "# SKIP: Already have '$outfile', not running '${cmd[*]}'; set REDO=1 to overwrite." &&
      exit 0
   noquiet " # Already have '$outfile' but overwritting: REDO=$REDO."
fi

# run the thing that should make the input
if [ $write_stdout -eq 0 ]; then
    dryrun "${cmd[@]}"
else
    dryrun "${cmd[@]}" | drytee "$outfile"
fi

# check that what we did worked
cmd_status=$?

# if there is an error (cmd_status > 0), should we still warn?
[[ ( $cmd_status -eq 0 && -s "$outfile" ) || -n "${DRYRUN:-}" ]] ||
   echo "# WARNING: '$outfile' DNE or is empty after '${cmd[*]}'" >&2

exit $cmd_status
